-- ============================================================
-- PROJECT 1: SALES DATA ANALYSIS USING SQL
-- File: 02_sample_data.sql
-- Purpose: Insert realistic sample data for analysis
-- ============================================================

-- Customers
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (1, 'Rahul Verma', 'rahul.verma1@example.com', 'Bengaluru', '2025-01-14');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (2, 'Saanvi Iyer', 'saanvi.iyer2@example.com', 'Pune', '2024-03-12');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (3, 'Sneha Verma', 'sneha.verma3@example.com', 'Jaipur', '2024-02-14');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (4, 'Meera Patel', 'meera.patel4@example.com', 'Bengaluru', '2024-01-16');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (5, 'Aditya Iyer', 'aditya.iyer5@example.com', 'Pune', '2024-09-15');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (6, 'Pooja Sharma', 'pooja.sharma6@example.com', 'Jaipur', '2024-04-11');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (7, 'Vikram Das', 'vikram.das7@example.com', 'Kolkata', '2024-04-22');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (8, 'Priya Mehta', 'priya.mehta8@example.com', 'Hyderabad', '2024-01-04');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (9, 'Nikhil Gupta', 'nikhil.gupta9@example.com', 'Kolkata', '2024-06-23');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (10, 'Saanvi Gupta', 'saanvi.gupta10@example.com', 'Pune', '2025-01-25');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (11, 'Aisha Verma', 'aisha.verma11@example.com', 'Mumbai', '2024-07-13');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (12, 'Ishaan Reddy', 'ishaan.reddy12@example.com', 'Chennai', '2024-11-05');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (13, 'Saanvi Sharma', 'saanvi.sharma13@example.com', 'Ahmedabad', '2024-10-01');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (14, 'Ishaan Patel', 'ishaan.patel14@example.com', 'Mumbai', '2024-10-09');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (15, 'Myra Mehta', 'myra.mehta15@example.com', 'Chennai', '2024-10-22');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (16, 'Ananya Verma', 'ananya.verma16@example.com', 'Bengaluru', '2024-12-04');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (17, 'Diya Nair', 'diya.nair17@example.com', 'Mumbai', '2024-04-29');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (18, 'Simran Verma', 'simran.verma18@example.com', 'Kolkata', '2024-05-22');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (19, 'Priya Reddy', 'priya.reddy19@example.com', 'Delhi', '2024-07-08');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (20, 'Kavya Iyer', 'kavya.iyer20@example.com', 'Hyderabad', '2024-12-25');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (21, 'Divya Verma', 'divya.verma21@example.com', 'Lucknow', '2024-11-21');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (22, 'Kabir Das', 'kabir.das22@example.com', 'Pune', '2024-03-24');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (23, 'Priya Patel', 'priya.patel23@example.com', 'Hyderabad', '2024-11-23');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (24, 'Vikram Das', 'vikram.das24@example.com', 'Pune', '2024-12-16');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (25, 'Aisha Sharma', 'aisha.sharma25@example.com', 'Pune', '2024-01-17');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (26, 'Tanya Reddy', 'tanya.reddy26@example.com', 'Kolkata', '2024-05-17');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (27, 'Aditya Iyer', 'aditya.iyer27@example.com', 'Lucknow', '2025-01-02');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (28, 'Aisha Iyer', 'aisha.iyer28@example.com', 'Ahmedabad', '2024-07-21');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (29, 'Amit Singh', 'amit.singh29@example.com', 'Delhi', '2024-05-15');
INSERT INTO customers (customer_id, customer_name, email, city, signup_date) VALUES (30, 'Rohan Iyer', 'rohan.iyer30@example.com', 'Jaipur', '2024-10-02');

-- Products
INSERT INTO products (product_id, product_name, category, price, cost) VALUES (1, 'Wireless Mouse', 'Electronics', 699, 350);
INSERT INTO products (product_id, product_name, category, price, cost) VALUES (2, 'Mechanical Keyboard', 'Electronics', 2499, 1400);
INSERT INTO products (product_id, product_name, category, price, cost) VALUES (3, 'USB-C Charger', 'Electronics', 999, 500);
INSERT INTO products (product_id, product_name, category, price, cost) VALUES (4, 'Bluetooth Earbuds', 'Electronics', 1999, 1000);
INSERT INTO products (product_id, product_name, category, price, cost) VALUES (5, 'Laptop Stand', 'Accessories', 1299, 600);
INSERT INTO products (product_id, product_name, category, price, cost) VALUES (6, 'Office Chair', 'Furniture', 7999, 4500);
INSERT INTO products (product_id, product_name, category, price, cost) VALUES (7, 'Standing Desk', 'Furniture', 14999, 9000);
INSERT INTO products (product_id, product_name, category, price, cost) VALUES (8, 'Notebook Set', 'Stationery', 299, 120);
INSERT INTO products (product_id, product_name, category, price, cost) VALUES (9, 'Desk Lamp', 'Accessories', 1499, 700);
INSERT INTO products (product_id, product_name, category, price, cost) VALUES (10, 'Webcam HD', 'Electronics', 2999, 1600);
INSERT INTO products (product_id, product_name, category, price, cost) VALUES (11, 'External SSD 1TB', 'Electronics', 6999, 4800);
INSERT INTO products (product_id, product_name, category, price, cost) VALUES (12, 'Backpack', 'Accessories', 1999, 900);
INSERT INTO products (product_id, product_name, category, price, cost) VALUES (13, 'Water Bottle', 'Accessories', 499, 200);
INSERT INTO products (product_id, product_name, category, price, cost) VALUES (14, 'Monitor 24-inch', 'Electronics', 10999, 7500);
INSERT INTO products (product_id, product_name, category, price, cost) VALUES (15, 'Desk Organizer', 'Stationery', 599, 250);

-- Orders
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (1, 1, '2025-10-27', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (2, 2, '2025-08-05', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (3, 2, '2025-05-17', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (4, 2, '2025-04-02', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (5, 2, '2025-11-08', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (6, 3, '2025-07-05', 'Cancelled');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (7, 4, '2025-02-05', 'Pending');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (8, 4, '2025-09-28', 'Cancelled');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (9, 4, '2025-07-24', 'Pending');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (10, 5, '2025-10-11', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (11, 6, '2025-01-17', 'Cancelled');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (12, 7, '2025-09-06', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (13, 8, '2025-04-08', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (14, 8, '2025-07-26', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (15, 8, '2025-08-18', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (16, 8, '2025-02-20', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (17, 9, '2025-04-20', 'Cancelled');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (18, 9, '2025-01-02', 'Pending');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (19, 10, '2025-04-22', 'Pending');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (20, 11, '2025-09-15', 'Cancelled');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (21, 11, '2025-02-05', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (22, 11, '2025-02-11', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (23, 12, '2025-12-10', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (24, 12, '2025-04-20', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (25, 13, '2025-10-06', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (26, 14, '2025-03-10', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (27, 14, '2025-05-25', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (28, 14, '2025-02-17', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (29, 14, '2025-10-10', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (30, 14, '2025-01-19', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (31, 15, '2025-04-18', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (32, 15, '2025-03-21', 'Cancelled');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (33, 15, '2025-01-13', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (34, 15, '2025-12-26', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (35, 15, '2025-08-24', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (36, 16, '2025-02-05', 'Pending');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (37, 17, '2025-05-14', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (38, 18, '2025-09-19', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (39, 18, '2025-10-03', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (40, 18, '2025-06-10', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (41, 19, '2025-12-23', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (42, 19, '2025-10-19', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (43, 20, '2025-11-07', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (44, 20, '2025-09-21', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (45, 20, '2025-03-17', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (46, 20, '2025-04-10', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (47, 21, '2025-12-23', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (48, 22, '2025-08-26', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (49, 23, '2025-09-01', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (50, 23, '2025-05-21', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (51, 23, '2025-04-29', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (52, 24, '2025-08-01', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (53, 24, '2025-06-02', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (54, 25, '2025-07-19', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (55, 25, '2025-11-26', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (56, 26, '2025-08-04', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (57, 27, '2025-02-05', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (58, 28, '2025-11-15', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (59, 28, '2025-12-25', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (60, 28, '2025-02-25', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (61, 28, '2025-12-20', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (62, 29, '2025-06-27', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (63, 29, '2025-08-10', 'Pending');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (64, 29, '2025-08-12', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (65, 29, '2025-10-19', 'Completed');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (66, 30, '2025-11-02', 'Completed');

-- Order Items
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (1, 1, 6, 2, 7999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (2, 1, 4, 1, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (3, 1, 3, 1, 999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (4, 1, 9, 1, 1499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (5, 2, 7, 2, 14999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (6, 2, 10, 3, 2999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (7, 2, 8, 1, 299);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (8, 2, 9, 3, 1499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (9, 3, 2, 1, 2499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (10, 3, 5, 2, 1299);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (11, 3, 7, 1, 14999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (12, 4, 14, 3, 10999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (13, 5, 13, 3, 499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (14, 5, 3, 1, 999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (15, 5, 9, 3, 1499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (16, 6, 4, 3, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (17, 6, 1, 1, 699);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (18, 6, 15, 1, 599);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (19, 7, 3, 2, 999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (20, 7, 11, 3, 6999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (21, 8, 4, 3, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (22, 8, 9, 1, 1499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (23, 8, 13, 3, 499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (24, 8, 12, 2, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (25, 9, 8, 1, 299);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (26, 9, 9, 1, 1499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (27, 9, 15, 1, 599);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (28, 10, 1, 3, 699);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (29, 10, 2, 3, 2499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (30, 11, 9, 1, 1499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (31, 12, 12, 3, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (32, 12, 10, 2, 2999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (33, 13, 6, 3, 7999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (34, 13, 7, 1, 14999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (35, 13, 14, 3, 10999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (36, 13, 8, 3, 299);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (37, 14, 4, 1, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (38, 15, 5, 1, 1299);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (39, 15, 8, 1, 299);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (40, 16, 2, 1, 2499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (41, 17, 3, 2, 999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (42, 18, 15, 2, 599);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (43, 18, 13, 2, 499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (44, 18, 14, 2, 10999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (45, 19, 12, 2, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (46, 20, 1, 1, 699);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (47, 20, 9, 1, 1499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (48, 21, 7, 3, 14999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (49, 21, 2, 1, 2499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (50, 22, 15, 3, 599);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (51, 22, 5, 3, 1299);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (52, 22, 4, 2, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (53, 23, 6, 2, 7999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (54, 23, 13, 3, 499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (55, 23, 2, 3, 2499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (56, 23, 1, 1, 699);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (57, 24, 15, 1, 599);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (58, 24, 6, 1, 7999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (59, 25, 11, 3, 6999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (60, 26, 12, 3, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (61, 27, 4, 2, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (62, 27, 11, 3, 6999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (63, 27, 14, 2, 10999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (64, 28, 1, 1, 699);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (65, 28, 15, 3, 599);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (66, 28, 6, 2, 7999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (67, 29, 2, 1, 2499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (68, 30, 7, 1, 14999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (69, 30, 3, 2, 999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (70, 31, 6, 3, 7999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (71, 32, 14, 1, 10999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (72, 32, 3, 2, 999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (73, 33, 13, 3, 499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (74, 33, 7, 3, 14999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (75, 33, 15, 1, 599);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (76, 34, 14, 2, 10999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (77, 35, 4, 3, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (78, 35, 1, 1, 699);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (79, 36, 6, 2, 7999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (80, 36, 11, 3, 6999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (81, 36, 9, 3, 1499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (82, 37, 1, 2, 699);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (83, 37, 2, 2, 2499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (84, 37, 10, 3, 2999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (85, 38, 5, 3, 1299);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (86, 38, 1, 2, 699);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (87, 39, 6, 1, 7999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (88, 39, 7, 3, 14999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (89, 40, 12, 2, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (90, 41, 4, 3, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (91, 41, 7, 2, 14999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (92, 42, 5, 2, 1299);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (93, 43, 8, 3, 299);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (94, 43, 15, 2, 599);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (95, 43, 11, 3, 6999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (96, 43, 4, 1, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (97, 44, 2, 1, 2499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (98, 44, 14, 3, 10999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (99, 44, 13, 2, 499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (100, 45, 8, 1, 299);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (101, 45, 10, 2, 2999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (102, 46, 8, 3, 299);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (103, 46, 7, 3, 14999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (104, 46, 4, 1, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (105, 46, 3, 1, 999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (106, 47, 9, 1, 1499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (107, 48, 13, 3, 499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (108, 48, 8, 3, 299);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (109, 48, 10, 2, 2999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (110, 49, 14, 2, 10999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (111, 49, 11, 3, 6999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (112, 50, 4, 2, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (113, 50, 5, 3, 1299);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (114, 50, 6, 1, 7999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (115, 51, 12, 1, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (116, 51, 4, 2, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (117, 52, 7, 1, 14999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (118, 52, 13, 3, 499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (119, 52, 10, 2, 2999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (120, 52, 12, 2, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (121, 53, 9, 3, 1499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (122, 53, 12, 1, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (123, 53, 14, 2, 10999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (124, 53, 15, 1, 599);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (125, 54, 12, 3, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (126, 54, 3, 3, 999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (127, 54, 8, 1, 299);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (128, 54, 14, 2, 10999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (129, 55, 3, 2, 999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (130, 55, 1, 1, 699);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (131, 55, 5, 2, 1299);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (132, 55, 7, 2, 14999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (133, 56, 8, 1, 299);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (134, 57, 13, 1, 499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (135, 58, 8, 1, 299);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (136, 58, 11, 3, 6999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (137, 59, 3, 3, 999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (138, 59, 10, 3, 2999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (139, 59, 14, 1, 10999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (140, 60, 10, 2, 2999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (141, 60, 11, 3, 6999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (142, 60, 7, 1, 14999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (143, 61, 2, 2, 2499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (144, 61, 12, 3, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (145, 62, 2, 2, 2499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (146, 62, 9, 1, 1499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (147, 62, 11, 2, 6999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (148, 63, 12, 3, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (149, 63, 3, 3, 999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (150, 63, 7, 3, 14999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (151, 63, 14, 2, 10999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (152, 64, 6, 1, 7999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (153, 64, 14, 2, 10999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (154, 64, 4, 2, 1999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (155, 65, 6, 1, 7999);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (156, 65, 1, 2, 699);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (157, 65, 8, 1, 299);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (158, 65, 15, 2, 599);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (159, 66, 9, 1, 1499);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (160, 66, 1, 1, 699);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price) VALUES (161, 66, 15, 1, 599);

-- Payments
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (1, 1, '2025-10-28', 20495, 'UPI');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (2, 2, '2025-08-05', 43791, 'Cash on Delivery');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (3, 3, '2025-05-19', 20096, 'Cash on Delivery');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (4, 4, '2025-04-04', 32997, 'Cash on Delivery');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (5, 5, '2025-11-10', 6993, 'Net Banking');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (6, 7, '2025-02-06', 22995, 'Debit Card');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (7, 9, '2025-07-24', 2397, 'Debit Card');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (8, 10, '2025-10-11', 9594, 'UPI');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (9, 12, '2025-09-07', 11995, 'Net Banking');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (10, 13, '2025-04-08', 72890, 'Credit Card');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (11, 14, '2025-07-27', 1999, 'Cash on Delivery');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (12, 15, '2025-08-21', 1598, 'Cash on Delivery');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (13, 16, '2025-02-21', 2499, 'Net Banking');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (14, 18, '2025-01-05', 24194, 'UPI');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (15, 19, '2025-04-22', 3998, 'Credit Card');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (16, 21, '2025-02-05', 47496, 'Cash on Delivery');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (17, 22, '2025-02-12', 9692, 'Debit Card');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (18, 23, '2025-12-10', 25691, 'Cash on Delivery');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (19, 24, '2025-04-22', 8598, 'Debit Card');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (20, 25, '2025-10-08', 20997, 'Credit Card');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (21, 26, '2025-03-11', 5997, 'Debit Card');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (22, 27, '2025-05-27', 46993, 'Credit Card');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (23, 28, '2025-02-18', 18494, 'Net Banking');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (24, 29, '2025-10-11', 2499, 'Cash on Delivery');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (25, 30, '2025-01-21', 16997, 'Credit Card');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (26, 31, '2025-04-21', 23997, 'Cash on Delivery');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (27, 33, '2025-01-15', 47093, 'UPI');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (28, 34, '2025-12-27', 21998, 'UPI');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (29, 35, '2025-08-27', 6696, 'Debit Card');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (30, 36, '2025-02-07', 41492, 'Credit Card');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (31, 37, '2025-05-16', 15393, 'Net Banking');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (32, 38, '2025-09-19', 5295, 'Cash on Delivery');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (33, 39, '2025-10-05', 52996, 'Cash on Delivery');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (34, 40, '2025-06-12', 3998, 'Net Banking');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (35, 41, '2025-12-24', 35995, 'Cash on Delivery');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (36, 42, '2025-10-20', 2598, 'Net Banking');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (37, 43, '2025-11-07', 25091, 'Debit Card');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (38, 44, '2025-09-22', 36494, 'UPI');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (39, 45, '2025-03-20', 6297, 'Cash on Delivery');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (40, 46, '2025-04-13', 48892, 'UPI');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (41, 47, '2025-12-23', 1499, 'Net Banking');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (42, 48, '2025-08-29', 8392, 'UPI');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (43, 49, '2025-09-04', 42995, 'UPI');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (44, 50, '2025-05-22', 15894, 'UPI');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (45, 51, '2025-05-02', 5997, 'Debit Card');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (46, 52, '2025-08-01', 26492, 'Debit Card');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (47, 53, '2025-06-04', 29093, 'Net Banking');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (48, 54, '2025-07-19', 31291, 'Credit Card');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (49, 55, '2025-11-28', 35293, 'Net Banking');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (50, 56, '2025-08-04', 299, 'Debit Card');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (51, 57, '2025-02-06', 499, 'UPI');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (52, 58, '2025-11-16', 21296, 'Net Banking');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (53, 59, '2025-12-26', 22993, 'Debit Card');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (54, 60, '2025-02-25', 41994, 'Cash on Delivery');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (55, 61, '2025-12-20', 10995, 'Cash on Delivery');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (56, 62, '2025-06-30', 20495, 'Credit Card');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (57, 63, '2025-08-13', 75989, 'Net Banking');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (58, 64, '2025-08-13', 33995, 'Net Banking');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (59, 65, '2025-10-21', 10894, 'Debit Card');
INSERT INTO payments (payment_id, order_id, payment_date, amount, payment_method) VALUES (60, 66, '2025-11-05', 2797, 'Net Banking');
